Console.WriteLine("i dont know what i am trying to learn today but  i think i will learn something");
float h=12345.09876f;
// Console.WriteLine(string.Format("{0;0}",h));
// Console.WriteLine(string.Format("{0;0.00}",h));
// Console.WriteLine(string.Format("{0;0.#}",h));
Console.WriteLine($"{h:0}");
Console.WriteLine($"{h:0.00}");
Console.WriteLine($"{h:0.#}");
Console.WriteLine(" i am soo fucking tired today .i cant even open my eyes");
Console.WriteLine("whats up with tokyo");
Console.WriteLine("i fucking didnt did anything today. just did some drawing on tab and  watched the series while doing it ");
Console.WriteLine("i think i did have happy day today somewhat . but i  think i didnt did anything productive .");